### ISSUE TITLE
Bug SimpleClans /.  

### ISSUE THREAD

**Issue by sritzboom** [RoinujNosde/SimpleClans#140]
I can't communicate through the clan chat and, when I try, this error occurs on the console

[22:42:01 WARN]: [SimpleClans] Task #367938 for SimpleClans v2.15.0 generated an exception
java.lang.NullPointerException: null
        at net.sacredlabyrinth.phaed.simpleclans.Helper.formatClanChat(Helper.java:885) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager$1.run(ClanManager.java:1224) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-451]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-451]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-451]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-451]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-451]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-451]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-451]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

  
  I just want to communicate in the clan chat

  Server:1.16.5
  SimpleClans 2.15.0

**Comment by RoinujNosde** [comment]
This should be fixed on the latest build: https://ci.codemc.io/job/RoinujNosde/job/SimpleClans/job/Dev/92/
