### ISSUE TITLE
PlayerInteractEvent error 

### ISSUE THREAD

**Issue by emanuelVINI01** [RoinujNosde/SimpleClans#223]
Onclick in any block, with plotsquared plugin in server, simpleclans throw NoSuchMethodException.

Log:
  [22:17:49 ERROR]: Could not pass event PlayerInteractEvent to SimpleClans v2.15.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_291]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.NoSuchMethodError: com.plotsquared.bukkit.util.BukkitUtil.getPlot(Lorg/bukkit/Location;)Lcom/plotsquared/core/plot/Plot;
        at net.sacredlabyrinth.phaed.simpleclans.hooks.protection.providers.PlotSquared5Provider.getLandsAt(PlotSquared5Provider.java:29) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.getLandsAt(ProtectionManager.java:76) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.can(ProtectionManager.java:104) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.can(ProtectionManager.java:100) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.listeners.LandProtection.onInteract(LandProtection.java:244) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
        ... 18 more
[22:17:49 ERROR]: Could not pass event PlayerInteractEvent to SimpleClans v2.15.2
java.lang.NoSuchMethodError: com.plotsquared.bukkit.util.BukkitUtil.getPlot(Lorg/bukkit/Location;)Lcom/plotsquared/core/plot/Plot;
        at net.sacredlabyrinth.phaed.simpleclans.hooks.protection.providers.PlotSquared5Provider.getLandsAt(PlotSquared5Provider.java:29) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.getLandsAt(ProtectionManager.java:76) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.can(ProtectionManager.java:104) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.can(ProtectionManager.java:100) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.listeners.LandProtection.lambda$registerInteractListener$6(LandProtection.java:181) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_291]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
[22:17:49 ERROR]: Could not pass event PlayerInteractEvent to SimpleClans v2.15.2
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_291]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
Caused by: java.lang.NoSuchMethodError: com.plotsquared.bukkit.util.BukkitUtil.getPlot(Lorg/bukkit/Location;)Lcom/plotsquared/core/plot/Plot;
        at net.sacredlabyrinth.phaed.simpleclans.hooks.protection.providers.PlotSquared5Provider.getLandsAt(PlotSquared5Provider.java:29) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.getLandsAt(ProtectionManager.java:76) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.can(ProtectionManager.java:104) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.can(ProtectionManager.java:100) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.listeners.LandProtection.onInteract(LandProtection.java:244) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]
        ... 18 more
[22:17:49 ERROR]: Could not pass event PlayerInteractEvent to SimpleClans v2.15.2
java.lang.NoSuchMethodError: com.plotsquared.bukkit.util.BukkitUtil.getPlot(Lorg/bukkit/Location;)Lcom/plotsquared/core/plot/Plot;
        at net.sacredlabyrinth.phaed.simpleclans.hooks.protection.providers.PlotSquared5Provider.getLandsAt(PlotSquared5Provider.java:29) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.getLandsAt(ProtectionManager.java:76) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.can(ProtectionManager.java:104) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.managers.ProtectionManager.can(ProtectionManager.java:100) ~[?:?]
        at net.sacredlabyrinth.phaed.simpleclans.listeners.LandProtection.lambda$registerInteractListener$6(LandProtection.java:181) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:623) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_291]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_291]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_291]
My plugins:
  AdvancedBan, AlwaysDay, ChestCommands, ChestShop, CoreData, CorePoints, HeroStackDrops, HolographicDisplays, HolographicExtension, JH_Economy, JH_Maquinas, JH_StackMobs, JH_Vender, MVdWPlaceholderAPI, MineResetLite, Multiverse-Core, MyCommand, NoCheatPlus, NoDropMine, PermissionsEx, PlaceholderAPI, PlayerPoints, PlotSquared, ProtocolLib, QuickBoard, SimpleClans, SkinsRestorer, System, TkCrSV, Vault, VipZero, WorldEdit, WorldGuard, nChat, nReport, vIUltimatePrefixos, zRankup

**Comment by RoinujNosde** [comment]
Remove PlotSquared5Provider from SimpleClans config.

**Comment by emanuelVINI01** [comment]
> Remove PlotSquared5Provider from SimpleClans config.

This not exist in configuration: 
safe-civilians: false
tag:
  default-color: '8'
  max-length: 5
  bracket:
    color: '8'
    leader-color: '4'
    left: ''
    right: ''
  min-length: 2
  separator:
    color: '8'
    leader-color: '4'
    char: ' .'
settings:
  enable-gui: false
  disable-messages: false
  tameable-mobs-sharing: false
  teleport-blocks: false
  teleport-home-on-spawn: false
  drop-items-on-clan-home: false
  keep-items-on-clan-home: false
  item-list: []
  show-debug-info: false
  mchat-integration: true
  enable-auto-groups: false
  chat-compatibility-mode: true
  rival-limit-percent: 50
  use-colorcode-from-prefix-for-name: true
  display-chat-tags: true
  unrivable-clans:
  - admin
  - staff
  - mod
  show-unverified-on-list: false
  blacklisted-worlds: []
  banned-players: []
  disallowed-tags:
  - vip
  - clan
  language: pt
  user-language-selector: true
  disallowed-tag-colors:
  - '4'
  server-name: '&4SimpleClans'
  new-clan-verification-required: false
  allow-regroup-command: true
  allow-reset-kdr: false
  rejoin-cooldown: 60
  rejoin-cooldown-enabled: false
  accept-other-alphabets-letters-on-tag: false
  ranking-type: DENSE
  list-default-order-by: kdr
  lore-length: 36
war-and-protection:
  war-enabled: false
  land-sharing: true
  protection-providers:
  - WorldGuard6Provider
  - PlotSquared3Provider
  listeners:
    priority: HIGHEST
    ignored-list:
      PLACE:
      - PLAYER_HEAD
  set-base-only-in-land: false
  war-normal-expiration-time: 0
  war-disconnect-expiration-time: 0
  edit-all-lands: false
  land-creation:
    only-leaders: false
    only-one-per-clan: false
  war-actions:
    CONTAINER: true
    INTERACT: true
    BREAK: true
    PLACE: true
    DAMAGE: true
    INTERACT_ENTITY: true
  war-start:
    request-enabled: true
    members-online-max-difference: 5
kdr-grinding-prevention:
  enable-max-kills: false
  max-kills-per-victim: 10
  enable-kill-delay: false
  delay-between-kills: 5
commands:
  more: more
  ally: ally
  clan: clan
  accept: accept
  deny: deny
  global: global
  clan_chat: .
  force-priority: true
economy:
  creation-price: 100.0
  purchase-clan-create: false
  verification-price: 1000.0
  purchase-clan-verify: false
  invite-price: 20.0
  purchase-clan-invite: false
  home-teleport-price: 5.0
  purchase-home-teleport: false
  home-teleport-set-price: 5.0
  purchase-home-teleport-set: false
  home-regroup-price: 5.0
  purchase-home-regroup: false
  unique-tax-on-regroup: true
  issuer-pays-regroup: true
  money-per-kill: false
  money-per-kill-kdr-multipier: 10
  purchase-reset-kdr: true
  reset-kdr-price: 10000.0
  purchase-member-fee-set: false
  member-fee-set-price: 1000.0
  member-fee-enabled: false
  member-fee-last-minute-change-interval: 8
  max-member-fee: 200.0
  upkeep: 200.0
  upkeep-enabled: false
  multiply-upkeep-by-clan-size: false
  charge-upkeep-only-if-member-fee-enabled: true
kill-weights:
  rival: 2.0
  civilian: 0.0
  neutral: 1.0
  ally: -1.0
  deny-same-ip-kills: false
clan:
  homebase-teleport-wait-secs: 10
  homebase-can-be-set-only-once: true
  min-size-to-set-rival: 3
  max-length: 25
  max-description-length: 120
  min-description-length: 10
  max-members: 25
  confirmation-for-promote: false
  trust-members-by-default: false
  confirmation-for-demote: false
  percentage-online-to-demote: 100.0
  ff-on-by-default: false
  min-length: 2
  max-alliances: -1
  min-size-to-set-ally: 3
  min-to-verify: 1
tasks:
  collect-upkeep:
    hour: 1
    minute: 30
  collect-upkeep-warning:
    hour: 12
    minute: 0
  collect-fee:
    hour: 1
    minute: 0
page:
  untrusted-color: '8'
  clan-name-color: b
  subtitle-color: '7'
  headings-color: '8'
  trusted-color: f
  leader-color: '4'
  separator: '-'
  size: 100
clanchat:
  enable: true
  tag-based-clan-chat: false
  announcement-color: e
  format: '&b[%clan%&b] &4<%nick-color%%player%&4> %rank%: &b%message%'
  rank: '&f[%rank%&f]'
  leader-color: '4'
  trusted-color: f
  member-color: '7'
request:
  message-color: b
  ask-frequency-secs: 60
  max-asks-per-request: 1440
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
  login-size: 6
allychat:
  enable: true
  format: '&b[Ally Chat] &4<%clan%&4> <%nick-color%%player%&4> %rank%: &b%message%'
  rank: '&f[%rank%&f]'
  leader-color: '4'
  trusted-color: f
  member-color: '7'
purge:
  inactive-player-data-days: 30
  inactive-clan-days: 7
  unverified-clan-days: 2
mysql:
  username: ''
  host: localhost
  port: 3306
  enable: false
  password: ''
  database: ''
permissions:
  auto-group-groupname: false
  YourClanNameHere:
  - test.permission
performance:
  save-periodically: true
  save-interval: 10
  use-threads: true
  use-bungeecord: false

**Comment by RoinujNosde** [comment]
Try restarting your server, then open the config and see if that option appeared.

You can also disable land-sharing if you are not using it.

**Comment by RoinujNosde** [comment]
8eaa86a
