### ISSUE TITLE
Erro ao baixar textura de cabeças dos jogadores

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/SimpleClans#324]
**Describe the bug**
Erro no console, começou após eu mudar do Waterfall para Velocity, lembrando que meu server esta usando a opção `online-mode: false`

**To Reproduce**
1. Utilizar Velocity como software para o proxy ao invés de waterfall?

**Expected behavior**
Nenhum erro no console.

**Software (please complete the following information):**
 - Server: [Pufferfish-72](https://ci.pufferfish.host/job/Pufferfish-1.18/)
 - Plugin version: 2.18.0-2647af2

**Additional context**
```
[16:44:49 ERROR]: Uncaught exception in thread Profile Lookup Executor #3
java.lang.RuntimeException: Original profile: 'com.mojang.authlib.GameProfile@784cb5c6[id=053e378b-99b3-3178-b520-7163c5dac0f3,name=AikaLivia,properties={},legacy=false]'
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:192) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.3.39.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$4(SkullBlockEntity.java:170) ~[?:?]
        at net.minecraft.Util.ifElse(Util.java:426) ~[?:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:167) ~[?:?]
        ... 3 more
        Suppressed: java.lang.Throwable: updateGameprofile caller debug trace
                at net.minecraft.world.level.block.entity.SkullBlockEntity.updateGameprofile(SkullBlockEntity.java:162) ~[?:?]
                at net.minecraft.world.level.block.entity.SkullBlockEntity.updateGameprofile(SkullBlockEntity.java:155) ~[?:?]
                at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:94) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
                at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:553) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
                at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
                at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventory.setItem(CraftInventory.java:99) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
                at net.sacredlabyrinth.phaed.simpleclans.tasks.PlayerHeadCacheTask.run(PlayerHeadCacheTask.java:53) ~[SimpleClans-2.18.0-2647af2.jar:?]
                at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
                at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
                at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by RoinujNosde** [comment]
Você usa Geyser?

**Comment by SrBedrock** [comment]
> Você usa Geyser?

comecei a usar junto com a troca do waterfall para o velocity, também pode ser o causador do problema, ou eu atingi o limite de requisições causada por outro plugin (PlayerWarps)

Se o causador for o PlayerWarps eu fecho esse issue, já estou verificando isso com o Dev responsável.

**Comment by RoinujNosde** [comment]
`allow-custom-skulls: true`
Essa função do Geyser causa o bug.
Desative, e se resolver o problema, reporta para o Geyser.

**Comment by RoinujNosde** [comment]
https://wiki.geysermc.org/geyser/current-limitations/
