### ISSUE TITLE
Error when accepting a request

### ISSUE THREAD

**Issue by AgeraFly** [RoinujNosde/SimpleClans#333]
**Describe the bug**
Im wanna accept clan ally and im get error "[SimpleClans] [ACF] Exception in command: accept"

**To Reproduce**
1. Run command "/clan ally CLANNAME"
2. Second player run a command "/clan accept" and get error 

**Expected behavior**
Add clan ally

**Screenshots**
What?

**Software (please complete the following information):**
 - Server: 1.19 Paper
 - Plugin version: 2.18.0

**Additional context**
```[19:11:57 ERROR]: [SimpleClans] [ACF] Exception in command: accept 
[19:11:57 ERROR]: [SimpleClans] [ACF] java.lang.NoSuchMethodError: 'com.mojang.authlib.yggdrasil.response.Response com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(java.net.URL, java.lang.Object, java.lang.Class)'
[19:11:57 ERROR]: [SimpleClans] [ACF]   at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:56)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfilesByNames(PaperGameProfileRepository.java:44)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.players.UserCache.a(UserCache.java:110)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.players.UserCache.a(UserCache.java:181)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at org.bukkit.craftbukkit.v1_19_R1.CraftServer.getOfflinePlayer(CraftServer.java:1812)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1239)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.uuid.UUIDMigration.getForcedPlayerUUID(UUIDMigration.java:39)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.managers.RequestManager.processResults(RequestManager.java:234)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.managers.RequestManager.accept(RequestManager.java:172)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.commands.general.GeneralCommands.accept(GeneralCommands.java:181)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.acf.BaseCommand.executeCommand(BaseCommand.java:577)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.acf.BaseCommand.execute(BaseCommand.java:513)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.acf.RootCommand.execute(RootCommand.java:99)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.acf.BukkitRootCommand.execute(BukkitRootCommand.java:84)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2382)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$18(PlayerConnection.java:2153)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1359)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1336)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1329)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1307)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1192)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[19:11:57 ERROR]: [SimpleClans] [ACF]   at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by RoinujNosde** [comment]
What is the paper build?

**Comment by AgeraFly** [comment]
![image](https://user-images.githubusercontent.com/65765314/197350817-9377a331-93fc-42c3-a317-bd45647b07ac.png)

**Comment by Mr666dd** [comment]
Please also note that when exiting the server of the clan leader with whom the alliance is concluded, writes:

***AgeraFly gave the go-ahead. The CREATE_ALLY request has been canceled.***

**Comment by RoinujNosde** [comment]
This seems to be a paper bug. I will test this when I get home.

**Comment by Mr666dd** [comment]
We are waiting for you!

**Comment by RoinujNosde** [comment]
Did some testing and I can't reproduce this issue.
My guess is you have some outdated paper library, so:
- stop your server
- delete the `libraries` folder
- start it again

**Comment by AgeraFly** [comment]
did not help. Could the problem be that we are using our own authlib?

**Comment by RoinujNosde** [comment]
It could be, yeah.
This method is missing from the authlib: `com.mojang.authlib.yggdrasil.response.Response com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(java.net.URL, java.lang.Object, java.lang.Class)`

**Comment by Mr666dd** [comment]
How can I rewrite the code so that this does not happen?

**Comment by RoinujNosde** [comment]
Add the missing method.

**Comment by AgeraFly** [comment]
Thank you for your time. I'll close the application for now, the problem here is in the **authlib**, and not in you.

Thanks! :)
