### ISSUE TITLE
Exception on Server Join with 1.20.2

### ISSUE THREAD

**Issue by sebseb7** [RoinujNosde/SimpleClans#402]
**Describe the bug**
exception at server join

**To Reproduce**
paper-1.20.2

**Screenshots**
```
[21:24:34 INFO]: [SimpleClans] [ACF] Can't read players locale, you will be unable to automatically detect players language. Only Bukkit 1.7+ is supported for this.
[21:24:34 INFO]: [SimpleClans] [ACF] java.lang.NoSuchFieldException: locale
[21:24:34 INFO]: [SimpleClans] [ACF]    at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[21:24:34 INFO]: [SimpleClans] [ACF]    at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.acf.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:324)
[21:24:34 INFO]: [SimpleClans] [ACF]    at SimpleClans.jar//net.sacredlabyrinth.phaed.simpleclans.acf.ACFBukkitListener.onPlayerJoin(ACFBukkitListener.java:57)
[21:24:34 INFO]: [SimpleClans] [ACF]    at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[21:24:34 INFO]: [SimpleClans] [ACF]    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[21:24:34 INFO]: [SimpleClans] [ACF]    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:24:34 INFO]: [SimpleClans] [ACF]    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:24:34 INFO]: [SimpleClans] [ACF]    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[21:24:34 INFO]: [SimpleClans] [ACF]    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.players.PlayerList.a(PlayerList.java:325)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1349)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1326)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1319)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1297)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1185)
[21:24:34 INFO]: [SimpleClans] [ACF]    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[21:24:34 INFO]: [SimpleClans] [ACF]    at java.base/java.lang.Thread.run(Thread.java:833)
```

**Software (please complete the following information):**
 - Server: paper-1.20.2
 - Plugin git head of SimpleClans

**Comment by RoinujNosde** [comment]
This is a bug in the library, but no real functionality is being lost.

You can safely ignore this error.

**Comment by SrBedrock** [comment]
It has already been reported https://github.com/aikar/commands/issues/402
