### ISSUE TITLE
O Plugin não está funcionando na 1.8x

### ISSUE THREAD

**Issue by ShizenXD** [RoinujNosde/SimpleClans#409]
[20:21:27 ERROR]: Could not load 'plugins\SimpleClans.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: net/sacredlabyrinth/phaed/simpleclans/SimpleClans has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:340) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:263) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:236) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_391]
Caused by: java.lang.UnsupportedClassVersionError: net/sacredlabyrinth/phaed/simpleclans/SimpleClans has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_391]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_391]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_391]
        at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_391]
        at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_391]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_391]
        at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_391]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_391]
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_391]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_391]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_391]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_391]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_391]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[patched_1.8.8.jar:git-PandaSpigot-115]
        ... 7 more

**Comment by SrBedrock** [comment]
@ShizenXD usa Java 16 ou 17
