### ISSUE TITLE
Console Error on player join

### ISSUE THREAD

**Issue by Peng1104** [RoinujNosde/SimpleClans#55]
**To Reproduce**
This bugs happens sometimes on when a player join the server

**Expected behavior**
Not print an error on the console and load the clan of the player

**Screenshots**
[01:20:57] [Server Thread/ERROR]: Error handling conversation prompt
java.lang.NullPointerException
	at net.sacredlabyrinth.phaed.simpleclans.conversation.ResignPrompt.acceptInput(ResignPrompt.java:36) ~[?:?]
	at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:229) [spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.conversations.ConversationTracker.acceptConversationInput(SourceFile:58) [spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.acceptConversationInput(SourceFile:1170) [spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.PlayerConnection$3.evaluate(SourceFile:1069) [spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(SourceFile:24) [spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.tickWorlds(SourceFile:872) [spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.tickWorlds(SourceFile:349) [spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.tickServer(SourceFile:790) [spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:669) [spigot.jar:git-iSpigot-PaperEdition]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_265]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_265]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_265]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_265]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

[08:10:03] [User Authenticator #34/INFO]: UUID of player TryTap is 96c2f86e-fe62-42d4-b0eb-ab6d7c798e9d
[08:10:03] [Server Thread/INFO]: net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.importClan(ClanManager.java:123)
[08:10:03] [Server Thread/INFO]: net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.retrieveOneClanPlayer(StorageManager.java:662)
[08:10:03] [Server Thread/INFO]: net.sacredlabyrinth.phaed.simpleclans.managers.StorageManager.importFromDatabaseOnePlayer(StorageManager.java:287)
[08:10:03] [Server Thread/INFO]: net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.getClanPlayerJoinEvent(ClanManager.java:267)
[08:10:03] [Server Thread/INFO]: net.sacredlabyrinth.phaed.simpleclans.listeners.SCPlayerListener.onPlayerJoin(SCPlayerListener.java:245)
[08:10:03] [Server Thread/INFO]: spg.lgdev.events.executor.asm.generated.GeneratedEventExecutor304.execute(Unknown Source)
[08:10:03] [Server Thread/INFO]: org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:68)
[08:10:03] [Server Thread/INFO]: co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[08:10:03] [Server Thread/INFO]: org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[08:10:03] [Server Thread/INFO]: org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:570)
[08:10:03] [Server Thread/INFO]: org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:549)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin0(SourceFile:332)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.PlayerList.a(SourceFile:168)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.LoginListener.b(SourceFile:150)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.LoginListener.c(SourceFile:53)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.NetworkManager.a(SourceFile:255)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.ServerConnection.c(SourceFile:116)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.MinecraftServer.tickWorlds(SourceFile:927)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.DedicatedServer.tickWorlds(SourceFile:349)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.MinecraftServer.tickServer(SourceFile:790)
[08:10:03] [Server Thread/INFO]: net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:669)
[08:10:03] [Server Thread/INFO]: java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[08:10:03] [Server Thread/INFO]: java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
[08:10:03] [Server Thread/INFO]: java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
[08:10:03] [Server Thread/INFO]: java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
[08:10:03] [Server Thread/INFO]: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:10:03] [Server Thread/INFO]: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:10:03] [Server Thread/INFO]: java.lang.Thread.run(Thread.java:748)

**Software (please complete the following information):**
 - Server: Spigot 1.8.8
 - Plugin version 2.13.1

**Additional context**

**Comment by RoinujNosde** [comment]
Poste o log completo do servidor no pastebin.com, por favor.

**Comment by RoinujNosde** [comment]
Talvez seja causado ao rodar /clan resign e relogar. TODO: testar
